version: '3.9'

services:
  home:
    build:
      context: ./home
    ports:
      - "8501:8501" 

  kid:
    build:
      context: ./kid
    ports:
      - "8502:8502"

  senior:
    build:
      context: ./senior
    ports:
      - "8503:8503"

  researcher:
    build:
      context: ./researcher
    ports:
      - "8504:8504"

  company:
    build:
      context: ./company
    ports:
      - "8505:8505"

  soldier:
    build:
      context: ./soldier
    ports:
      - "8506:8506"

  job:
    build:
      context: ./job
    ports:
      - "8507:8507"